import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '@/lib/AntdRegistry'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { Providers } from '@/store/StoreProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <StyledComponentsRegistry>
            <Navbar/>
            {children}
            <Footer/>
          </StyledComponentsRegistry>
        </body>
      </html>
    </Providers>
    
  )
}
